apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 952723044475.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 952723044475.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: b037cd37
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
